name: Task2
on:
  push:
    branches: [main, develop]
  pull_request: 
    branches: [develop]
  workflow_dispatch:
jobs:
    say-hello-job:
        runs-on: ubuntu-latest
        steps:
          - name: SayHello
            run: echo "Hello, GitHub Actions!"
    
    test-coverage:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up python
            uses: action/setup-python@v5
            with:
              python-version: "3.14.6"

          - name: Run tests and check coverage
            run: pytest --cov=myapp --cov-fail-under=70 > coverage-report.txt

          - name: Upload coverage report
            uses: actions/upload-artifact@v4
            with:
              name: python-coverage-report
              path: coverage-report.txt

